SELECT
    ROWNUM AS ID, SQ.* FROM
    (SELECT elad.id,
            LD_DATE_OF_COMPLIANCE,
            (LD_ADVICE_OTHER).getClobVal(),
            (LD_ADVICE_COUNTRY_LIST).getClobVal(),
            (LD_ADVICE_SIGNATORY_DET).getClobVal(),
            (LD_ADVICE_CASE_ALLOC).getClobVal(),
            PRECC_END_USE_DOCS_FLAG,
            PRECC_RFD_CERT_OK_FLAG,
            PRECC_FIREARMS_CERT_OK_FLAG,
            PRECC_REFUSALS_MATCH_FLAG,
            PRECC_UNSCR_MATCH_FLAG,
            PRECC_INCORP_FLAG,
            PRECC_PRIOR_IMP_CONS_REQ,
            POSTCC_REFUSALS_MATCH_FLAG,
            POSTCC_UNSCR_MATCH_FLAG,
            POSTCC_WL_MATCH_FLAG,
            DENIALS_POSSIBLE_MATCH_FLAG,
            DENIALS_MATCH_CHECKED_FLAG,
            (DENIALS_MATCH_LIST).getClobVal(),
            (EU_CONCERNS_LIST).getClobVal(),
            OGL_ELIG_FLAG,
            (OGL_ELIG_OGL_TYPE_LIST).getClobVal(),
            GR_TAU_COMMENT,
            GR_ADVICE_POSSIBLE,
            GR_NLR_TYPE,
            GR_ENDORSED_LIST_FLAG,
            GR_NLR_TYPE_IRAN,
            GR_SUPERSEDE_RESPONSE_DATE,
            GR_SUPERSEDE_TYPE,
            COMPL_LEVEL,
            COMPL_PROFILE_SINCE,
            COMPL_PROFILE_SINCE_DIFF,
            COMPL_LAST_VISIT_DATE,
            COMPL_LAST_VISIT_DATE_DIFF,
            COMPL_OFFICER,
            COMPL_OFFICER_DIFF,
            COMPL_FUT_OIEL_CONS,
            COMPL_FUT_OIEL_CONS_DIFF,
            COMPL_LU_NOTES,
            (COMPL_CONTEXT).getClobVal(),
            COMPL_VISIT_ID,
            COMPL_DATE_RETRIEVED,
            COMPL_WARN_ACTIVITIES,
            (GOODS_CLASS_REGIME_ORIGIN_LIST).getClobVal(),
            (GOODS_CLASS_LEGISL_ORIGIN_LIST).getClobVal(),
            (GOODS_CLASS_GOODS_RELATED_LIST).getClobVal(),
            GOODS_CLASS_AUTO_POPULATED,
            (MEDIA_FOOTNOTE_LIST).getClobVal(),
            TRADE_LIC_SUIT_ACT_DESC,
            OPEN_LIC_SUIT_BUS_CASE_FLAG,
            OPEN_LIC_COMPLIANCE_OK_FLAG,
            OPEN_LIC_SUITABILITY_COMMENT,
            RATING_CHECKS_UNSCR_MATCH_FLAG,
            DP_CHECKS_DP_MATCH_FLAG,
            (COUNTRY_RESTRICTION_LIST).getClobVal()
     FROM spiremgr.export_licence_app_details elad,
          xmltable('/*' PASSING elad.xml_data COLUMNS
              LD_DATE_OF_COMPLIANCE VARCHAR(4000) PATH '/*/CASE_DETAILS/LEGACY_DATA/DATE_OF_COMPLIANCE/text()',
              LD_ADVICE_OTHER XMLType PATH '/*/CASE_DETAILS/LEGACY_DATA/LEGACY_ADVICE/OTHER_ADVICE_LIST',
              LD_ADVICE_COUNTRY_LIST XMLType PATH '/*/CASE_DETAILS/LEGACY_DATA/LEGACY_ADVICE/COUNTRY_LIST',
              LD_ADVICE_SIGNATORY_DET XMLType PATH '/*/CASE_DETAILS/LEGACY_DATA/LEGACY_SIGNATORY_DETAILS',
              LD_ADVICE_CASE_ALLOC XMLType PATH '/*/CASE_DETAILS/LEGACY_DATA/LEGACY_CASE_ALLOCATION',
              PRECC_END_USE_DOCS_FLAG VARCHAR(4000) PATH '/*/CASE_DETAILS/PRE_CIRCULATION_CHECKS/END_USE_DOCS_FLAG/text()',
              PRECC_RFD_CERT_OK_FLAG VARCHAR(4000) PATH '/*/CASE_DETAILS/PRE_CIRCULATION_CHECKS/RFD_CERTIFCATE_OK_FLAG/text()',
              PRECC_FIREARMS_CERT_OK_FLAG VARCHAR(4000) PATH '/*/CASE_DETAILS/PRE_CIRCULATION_CHECKS/FIREARMS_CERTIFCATE_OK_FLAG/text()',
              PRECC_REFUSALS_MATCH_FLAG VARCHAR(4000) PATH '/*/CASE_DETAILS/PRE_CIRCULATION_CHECKS/REFUSALS_MATCH_FLAG/text()',
              PRECC_UNSCR_MATCH_FLAG VARCHAR(4000) PATH '/*/CASE_DETAILS/PRE_CIRCULATION_CHECKS/UNSCR_MATCH_FLAG/text()',
              PRECC_INCORP_FLAG VARCHAR(4000) PATH '/*/CASE_DETAILS/PRE_CIRCULATION_CHECKS/INCORPORATION_FLAG/text()',
              PRECC_PRIOR_IMP_CONS_REQ VARCHAR(4000) PATH '/*/CASE_DETAILS/PRE_CIRCULATION_CHECKS/PRIOR_IMPORT_CONSENT_REQUIRED/text()',
              POSTCC_REFUSALS_MATCH_FLAG VARCHAR(4000) PATH '/*/CASE_DETAILS/POST_CIRCULATION_CHECKS/REFUSALS_MATCH_FLAG/text()',
              POSTCC_UNSCR_MATCH_FLAG VARCHAR(4000) PATH '/*/CASE_DETAILS/POST_CIRCULATION_CHECKS/UNSCR_MATCH_FLAG/text()',
              POSTCC_WL_MATCH_FLAG VARCHAR(4000) PATH '/*/CASE_DETAILS/POST_CIRCULATION_CHECKS/WL_MATCH_FLAG/text()',
              DENIALS_POSSIBLE_MATCH_FLAG VARCHAR(4000) PATH '/*/CASE_DETAILS/DENIALS/POSSIBLE_MATCH_FLAG/text()',
              DENIALS_MATCH_CHECKED_FLAG VARCHAR(4000) PATH '/*/CASE_DETAILS/DENIALS/MATCH_CHECKED_FLAG/text()',
              DENIALS_MATCH_LIST XMLType PATH '/*/CASE_DETAILS/DENIALS/DENIALS_MATCH_LIST',
              EU_CONCERNS_LIST XMLType PATH '/*/CASE_DETAILS/ENFORCEMENT_UNIT/EU_CONCERNS_LIST',
              OGL_ELIG_FLAG VARCHAR(4000) PATH '/*/CASE_DETAILS/OGL_ELIGIBILITY/OGL_ELIGIBILITY_FLAG/text()',
              OGL_ELIG_OGL_TYPE_LIST XMLType PATH '/*/CASE_DETAILS/OGL_ELIGIBILITY/OGL_TYPE_LIST',
              GR_TAU_COMMENT VARCHAR(4000) PATH '/*/CASE_DETAILS/GOODS_RATING/TAU_COMMENT/text()',
              GR_ADVICE_POSSIBLE VARCHAR(4000) PATH '/*/CASE_DETAILS/GOODS_RATING/ADVICE_POSSIBLE/text()',
              GR_NLR_TYPE VARCHAR(4000) PATH '/*/CASE_DETAILS/GOODS_RATING/NLR_TYPE/text()',
              GR_ENDORSED_LIST_FLAG VARCHAR(4000) PATH '/*/CASE_DETAILS/GOODS_RATING/ENDORSED_LIST_FLAG/text()',
              GR_NLR_TYPE_IRAN VARCHAR(4000) PATH '/*/CASE_DETAILS/GOODS_RATING/NLR_TYPE_IRAN/text()',
              GR_SUPERSEDE_RESPONSE_DATE VARCHAR(4000) PATH '/*/CASE_DETAILS/GOODS_RATING/SUPERSEDE_RESPONSE_DATE/text()',
              GR_SUPERSEDE_TYPE VARCHAR(4000) PATH '/*/CASE_DETAILS/GOODS_RATING/SUPERSEDE_TYPE/text()',
              COMPL_LEVEL VARCHAR(4000) PATH '/*/CASE_DETAILS/COMPLIANCE/COMPLIANCE_LEVEL/text()',
              COMPL_PROFILE_SINCE VARCHAR(4000) PATH '/*/CASE_DETAILS/COMPLIANCE/PROFILE_SINCE/text()',
              COMPL_PROFILE_SINCE_DIFF VARCHAR(4000) PATH '/*/CASE_DETAILS/COMPLIANCE/PROFILE_SINCE_DIFF/text()',
              COMPL_LAST_VISIT_DATE VARCHAR(4000) PATH '/*/CASE_DETAILS/COMPLIANCE/LAST_VISIT_DATE/text()',
              COMPL_LAST_VISIT_DATE_DIFF VARCHAR(4000) PATH '/*/CASE_DETAILS/COMPLIANCE/LAST_VISIT_DATE_DIFF/text()',
              COMPL_OFFICER VARCHAR(4000) PATH '/*/CASE_DETAILS/COMPLIANCE/COMPLIANCE_OFFICER/text()',
              COMPL_OFFICER_DIFF VARCHAR(4000) PATH '/*/CASE_DETAILS/COMPLIANCE/COMPLIANCE_OFFICER_DIFF/text()',
              COMPL_FUT_OIEL_CONS VARCHAR(4000) PATH '/*/CASE_DETAILS/COMPLIANCE/FUTURE_OIEL_CONSIDERATION/text()',
              COMPL_FUT_OIEL_CONS_DIFF VARCHAR(4000) PATH '/*/CASE_DETAILS/COMPLIANCE/FUTURE_OIEL_CONSIDERATION_DIFF/text()',
              COMPL_LU_NOTES VARCHAR(4000) PATH '/*/CASE_DETAILS/COMPLIANCE/LU_NOTES/text()',
              COMPL_CONTEXT XMLType PATH '/*/CASE_DETAILS/COMPLIANCE/CONTEXT',
              COMPL_VISIT_ID VARCHAR(4000) PATH '/*/CASE_DETAILS/COMPLIANCE/VISIT_ID/text()',
              COMPL_DATE_RETRIEVED VARCHAR(4000) PATH '/*/CASE_DETAILS/COMPLIANCE/DATE_RETRIEVED/text()',
              COMPL_WARN_ACTIVITIES VARCHAR(4000) PATH '/*/CASE_DETAILS/COMPLIANCE/WARNING_ACTIVITIES/text()',
              GOODS_CLASS_REGIME_ORIGIN_LIST XMLType PATH '/*/CASE_DETAILS/GOODS_CLASSIFICATION/REGIME_ORIGIN_LIST',
              GOODS_CLASS_LEGISL_ORIGIN_LIST XMLType PATH '/*/CASE_DETAILS/GOODS_CLASSIFICATION/LEGISLATION_ORIGIN_LIST',
              GOODS_CLASS_GOODS_RELATED_LIST XMLType PATH '/*/CASE_DETAILS/GOODS_CLASSIFICATION/GOODS_RELATED_LIST',
              GOODS_CLASS_AUTO_POPULATED VARCHAR(4000) PATH '/*/CASE_DETAILS/GOODS_CLASSIFICATION/AUTO_POPULATED_CLASSIFICATION_LIST/text()',
              MEDIA_FOOTNOTE_LIST XMLType PATH '/*/CASE_DETAILS/MEDIA_FOOTNOTE_LIST',
              TRADE_LIC_SUIT_ACT_DESC VARCHAR(4000) PATH '/*/CASE_DETAILS/TRADE_LICENCE_SUITABILITY/TRADE_ACTIVITY_DESCRIPTION/text()',
              OPEN_LIC_SUIT_BUS_CASE_FLAG VARCHAR(4000) PATH '/*/CASE_DETAILS/OPEN_LICENCE_SUITABLITY/BUSINESS_CASE_FLAG/text()',
              OPEN_LIC_COMPLIANCE_OK_FLAG VARCHAR(4000) PATH '/*/CASE_DETAILS/OPEN_LICENCE_SUITABLITY/COMPLIANCE_OK_FLAG/text()',
              OPEN_LIC_SUITABILITY_COMMENT VARCHAR(4000) PATH '/*/CASE_DETAILS/OPEN_LICENCE_SUITABLITY/SUITABILITY_COMMENT/text()',
              RATING_CHECKS_UNSCR_MATCH_FLAG VARCHAR(4000) PATH '/*/CASE_DETAILS/RATING_CHECKS/UNSCR_MATCH_FLAG/text()',
              DP_CHECKS_DP_MATCH_FLAG VARCHAR(4000) PATH '/*/CASE_DETAILS/DP_CHECKS/DP_MATCH_FLAG/text()',
              COUNTRY_RESTRICTION_LIST XMLType PATH '/*/CASE_DETAILS/COUNTRY_RESTRICTION_LIST'
              ) xdet
     WHERE NOT (
             LD_DATE_OF_COMPLIANCE IS NULL AND
             LD_ADVICE_OTHER IS NULL AND
             LD_ADVICE_COUNTRY_LIST IS NULL AND
             LD_ADVICE_SIGNATORY_DET IS NULL AND
             LD_ADVICE_CASE_ALLOC IS NULL AND
             PRECC_END_USE_DOCS_FLAG IS NULL AND
             PRECC_RFD_CERT_OK_FLAG IS NULL AND
             PRECC_FIREARMS_CERT_OK_FLAG IS NULL AND
             PRECC_REFUSALS_MATCH_FLAG IS NULL AND
             PRECC_UNSCR_MATCH_FLAG IS NULL AND
             PRECC_INCORP_FLAG IS NULL AND
             PRECC_PRIOR_IMP_CONS_REQ IS NULL AND
             POSTCC_REFUSALS_MATCH_FLAG IS NULL AND
             POSTCC_UNSCR_MATCH_FLAG IS NULL AND
             POSTCC_WL_MATCH_FLAG IS NULL AND
             DENIALS_POSSIBLE_MATCH_FLAG IS NULL AND
             DENIALS_MATCH_CHECKED_FLAG IS NULL AND
             DENIALS_MATCH_LIST IS NULL AND
             EU_CONCERNS_LIST IS NULL AND
             OGL_ELIG_FLAG IS NULL AND
             OGL_ELIG_OGL_TYPE_LIST IS NULL AND
             GR_TAU_COMMENT IS NULL AND
             GR_ADVICE_POSSIBLE IS NULL AND
             GR_NLR_TYPE IS NULL AND
             GR_ENDORSED_LIST_FLAG IS NULL AND
             GR_NLR_TYPE_IRAN IS NULL AND
             GR_SUPERSEDE_RESPONSE_DATE IS NULL AND
             GR_SUPERSEDE_TYPE IS NULL AND
             COMPL_LEVEL IS NULL AND
             COMPL_PROFILE_SINCE IS NULL AND
             COMPL_PROFILE_SINCE_DIFF IS NULL AND
             COMPL_LAST_VISIT_DATE IS NULL AND
             COMPL_LAST_VISIT_DATE_DIFF IS NULL AND
             COMPL_OFFICER IS NULL AND
             COMPL_OFFICER_DIFF IS NULL AND
             COMPL_FUT_OIEL_CONS IS NULL AND
             COMPL_FUT_OIEL_CONS_DIFF IS NULL AND
             COMPL_LU_NOTES IS NULL AND
             COMPL_CONTEXT IS NULL AND
             COMPL_VISIT_ID IS NULL AND
             COMPL_DATE_RETRIEVED IS NULL AND
             COMPL_WARN_ACTIVITIES IS NULL AND
             GOODS_CLASS_REGIME_ORIGIN_LIST IS NULL AND
             GOODS_CLASS_LEGISL_ORIGIN_LIST IS NULL AND
             GOODS_CLASS_GOODS_RELATED_LIST IS NULL AND
             GOODS_CLASS_AUTO_POPULATED IS NULL AND
             MEDIA_FOOTNOTE_LIST IS NULL AND
             TRADE_LIC_SUIT_ACT_DESC IS NULL AND
             OPEN_LIC_SUIT_BUS_CASE_FLAG IS NULL AND
             OPEN_LIC_COMPLIANCE_OK_FLAG IS NULL AND
             OPEN_LIC_SUITABILITY_COMMENT IS NULL AND
             RATING_CHECKS_UNSCR_MATCH_FLAG IS NULL AND
             DP_CHECKS_DP_MATCH_FLAG IS NULL AND
             COUNTRY_RESTRICTION_LIST IS NULL
         )
     ORDER BY elad.id {LIMIT}) SQ
