SELECT
    ID,
    ELA_GRP_ID,
    LICENCE_REF,
    LICENCE_STATUS,
    START_DATE,
    END_DATE,
    NULL, -- (XML_DATA).getClobVal() XML_DATA,
    XP.GET(XML_DATA, '/*/OGL/OGL_TYPE') OGL_TYPE,
    XP.GET(XML_DATA, '/*/OGL/OGL_TITLE') OGL_TITLE
FROM SPIREMGR.EXPORT_LICENCES
ORDER BY ID {LIMIT}
